# Generated by Django 5.2.12 on 2026-03-25 06:05

import apps.ota.infrastructure.orm_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Semantic version string, e.g. 1.2.0', max_length=20, unique=True)),
                ('apk_file', models.FileField(help_text='Upload the APK file (max 200 MB).', upload_to='apks/', validators=[apps.ota.infrastructure.orm_models.validate_apk_size, apps.ota.infrastructure.orm_models.validate_apk_extension])),
                ('force_update', models.BooleanField(default=False, help_text='If True, the Flutter app must update before continuing.')),
                ('changelog', models.TextField(blank=True, help_text='What changed in this release (optional).')),
                ('min_supported_version', models.CharField(blank=True, help_text='Minimum app version that can update to this release (optional).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'App Update',
                'verbose_name_plural': 'App Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
