# Generated by Django 5.2.12 on 2026-03-30 13:26

import apps.ota.infrastructure.orm_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable app name, e.g. 'Merchant App'.", max_length=100)),
                ('package_name', models.CharField(help_text="Android package identifier, e.g. 'com.example.merchant'.", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional short description of this app.')),
                ('icon', models.ImageField(blank=True, help_text='Optional app icon (PNG/JPG, recommended 512×512).', null=True, upload_to='app_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mobile App',
                'verbose_name_plural': 'Mobile Apps',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Semantic version string, e.g. 1.2.0', max_length=20)),
                ('apk_file', models.FileField(help_text='Upload the APK file (max 500 MB).', upload_to=apps.ota.infrastructure.orm_models.apk_upload_path, validators=[apps.ota.infrastructure.orm_models.validate_apk_size, apps.ota.infrastructure.orm_models.validate_apk_extension])),
                ('checksum_sha256', models.CharField(blank=True, help_text='Integrity checksum of the uploaded APK (SHA-256).', max_length=64)),
                ('is_pinned', models.BooleanField(default=False, help_text='If True, treat this release as pinned/promoted regardless of recency.')),
                ('force_update', models.BooleanField(default=False, help_text='If True, the Flutter app must update before continuing.')),
                ('changelog', models.TextField(blank=True, help_text='What changed in this release (optional).')),
                ('min_supported_version', models.CharField(blank=True, help_text='Minimum app version that can update to this release (optional).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(blank=True, help_text='The mobile app this release belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='ota.mobileapp')),
            ],
            options={
                'verbose_name': 'App Release',
                'verbose_name_plural': 'App Releases',
                'ordering': ['-created_at'],
                'unique_together': {('app', 'version')},
            },
        ),
    ]
