# Generated by assistant to add build_number
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ota", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appupdate",
            name="build_number",
            field=models.IntegerField(blank=True, null=True, db_index=True, help_text="Integer build number auto-incremented per app (read-only)."),
        ),
        migrations.AlterUniqueTogether(
            name="appupdate",
            unique_together={("app", "version"), ("app", "build_number")},
        ),
    ]
