# Generated by Django 5.2.11 on 2026-03-29 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable app name, e.g. 'Merchant App'.", max_length=100)),
                ('package_name', models.CharField(help_text="Android package identifier, e.g. 'com.example.merchant'.", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional short description of this app.')),
                ('icon', models.ImageField(blank=True, help_text='Optional app icon (PNG/JPG, recommended 512×512).', null=True, upload_to='app_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mobile App',
                'verbose_name_plural': 'Mobile Apps',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='appupdate',
            options={'ordering': ['-created_at'], 'verbose_name': 'App Release', 'verbose_name_plural': 'App Releases'},
        ),
        migrations.AlterField(
            model_name='appupdate',
            name='version',
            field=models.CharField(help_text='Semantic version string, e.g. 1.2.0', max_length=20),
        ),
        migrations.AddField(
            model_name='appupdate',
            name='app',
            field=models.ForeignKey(blank=True, help_text='The mobile app this release belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='ota.mobileapp'),
        ),
        migrations.AlterUniqueTogether(
            name='appupdate',
            unique_together={('app', 'version')},
        ),
    ]
