# Generated by Django 5.2.12 on 2026-03-30

import apps.ota.infrastructure.orm_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0002_mobileapp_alter_appupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appupdate',
            name='apk_file',
            field=models.FileField(
                help_text='Upload the APK file (max 500 MB).',
                upload_to=apps.ota.infrastructure.orm_models.apk_upload_path,
                validators=[
                    apps.ota.infrastructure.orm_models.validate_apk_size,
                    apps.ota.infrastructure.orm_models.validate_apk_extension,
                ],
            ),
        ),
    ]
