# Generated by assistant: add public_id and backfill
from django.db import migrations, models
import uuid


def gen_uuids(apps, schema_editor):
    AppUpdate = apps.get_model('ota', 'AppUpdate')
    for obj in AppUpdate.objects.filter(public_id__isnull=True):
        obj.public_id = str(uuid.uuid4())
        obj.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0002_add_build_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appupdate',
            name='public_id',
            field=models.CharField(max_length=36, null=True, blank=True, unique=True, help_text='Opaque UUID used in public download URLs.'),
        ),
        migrations.RunPython(gen_uuids, reverse_code=migrations.RunPython.noop),
    ]
