# Generated by Django 5.2.12 on 2026-03-30

import apps.ota.infrastructure.orm_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0003_alter_appupdate_apk_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='appupdate',
            name='checksum_sha256',
            field=models.CharField(blank=True, help_text='Integrity checksum of the uploaded APK (SHA-256).', max_length=64),
        ),
        migrations.AddField(
            model_name='appupdate',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='If True, treat this release as pinned/promoted regardless of recency.'),
        ),
    ]
