name: inapp_update_manager
description: A reusable in-app OTA update manager using ota_update and clean architecture.
version: 0.0.1
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ota_update: ^7.1.0
  package_info_plus: ^4.0.0
  http: ^0.13.6
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

