name: ota-services
services:

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ota_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    entrypoint: ["sh"]
    command: ["-c", 'minio server /data --console-address :9001 & MINIO_PID=$$! ; sleep 5 ; mc alias set local http://localhost:9000 minioadmin minioadmin ; mc mb local/ota-media 2>/dev/null || true ; mc anonymous set public local/ota-media ; wait $$MINIO_PID']
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    volumes:
      - ../../:/app
      - media_data:/app/media
    ports:
      - "8003:8000"

    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

    environment:
      DEBUG: "True"
      SECRET_KEY: "change-me-local-dev"

      POSTGRES_DB: ota_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

      MINIO_ENDPOINT_URL: http://minio:9000
      MEDIA_PUBLIC_BASE_URL: "http://localhost:9000"
      MINIO_BUCKET_NAME: ota-media
      MINIO_ACCESS_KEY_ID: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_REGION_NAME: us-east-1
      MINIO_USE_SSL: "False"

    command: >
      sh -c "
      sleep 5 &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    restart: unless-stopped

volumes:
  postgres_data:
  media_data:
  minio_data: