name: inapp_update_manager

services:
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../../.env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    volumes:
      - ../../:/app
      - media_data:/app/media
    ports:
      - "8003:8000"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - ../../.env
    environment:
      - DEBUG
      - SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - MINIO_ENDPOINT_URL
      - MEDIA_PUBLIC_BASE_URL
      - MINIO_BUCKET_NAME
      - MINIO_ACCESS_KEY_ID
      - MINIO_SECRET_KEY
      - MINIO_REGION_NAME
      - MINIO_USE_SSL

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 300
      "
    restart: unless-stopped

volumes:
  postgres_data:
  media_data:
  minio_data:
